import React, { useContext, useEffect, useState } from "react"
import Navbar from "./components/organ/Navbar";
import DetailImage from './assets/detail.png'
import Image from "next/image";
import Head from "next/head";
import Button from "./components/atom/Button";
import { LeftOutlined, DeleteOutlined } from '@ant-design/icons/lib/icons'
import Link from "next/link";
import { useRouter } from "next/router";
import { RootContext } from "./components/reducer";
import { Modal, Input, Card } from "antd";


const Detail = () => {
    const {dispatch, state} = useContext(RootContext)
    let {id}= useRouter().query

    const [list, setList] = useState('')
    const [quantity, setQuantity] = useState('')
    const [open, setOpen] = useState(false)

    const message1 = {
        list : list,
        quantity : quantity
    }
    const handleOpen = () => {
        setOpen(true)
      }
      const handleCancel = () => {
        setOpen(false)
      } 
      const handleOk = () => {
        setList('')
        setQuantity('')
        console.log(list)
        dispatch({type:'ADD_ITEM', payload :message1, index : id })
        setOpen(false);
        // localStorage.setItem('state', JSON.stringify(state))
      }

    const handleDeteleItem = (props :string) => {
        dispatch({type : 'DELETE_ITEM', index : id, payload : props})
        // localStorage.setItem('state', JSON.stringify(state))
    }

    useEffect(() => {
        if(state.items.filter(item => item !== null)) {
            localStorage.setItem('state', JSON.stringify(state))
        }
    },[state])
    // console.log(state.items[0].id)
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>
                
                <div className='mx-36 pt-10 flex justify-between'>
                    <div className="text-3xl font-semibold flex justify-between items-center">
                        <Link href= '/'>
                            <LeftOutlined />
                        </Link>
                        Actifity
                    </div>
                    <Button
                        onClick={handleOpen}
                        className = 'text-lg font-semibold'
                    >
                        Tambah
                    </Button>
                </div>
                {state.items.map(item => {
                    if(item?.id == id) {
                        return(
                            <div key={item.id}>
                                {item.message[0]?.list ? item.message.map((list, number) => {
                                    return(
                                        <div key={number} className='flex flex-col gap-4 mx-36 pt-10'>
                                            {/* <CardDetail title = {list} onClick= {() =>  handleDeteleItem(list.list)} /> */}
                                            <Card className='w-[700px]' >
                                                <div className='flex justify-between items-center text-xl font-semibold'>
                                                    <div>
                                                        <p>List :{list.list}</p>
                                                        <p>Quantity:{list.quantity}</p>
                                                    </div>
                                                    <div onClick={() => handleDeteleItem(list.list)}>
                                                        <DeleteOutlined />
                                                    </div>
                                                </div>
                                            </Card>
                                        </div>
                                    )
                                      
                                }) :
                                <div className='mx-36 pt-10 flex justify-center'>
                                    <Image src={DetailImage} alt = 'detail' width={500} />
                                </div>}
                            </div>
                        )
                    }
                })}

                <Modal
                    title = 'Add Group'
                    open ={open}
                    onCancel ={handleCancel} 
                    onOk={handleOk}
                >
                    <div className="flex flex-col gap-4">
                        <p>Group List</p>
                        <label>
                            Masukan List :
                            <Input
                                placeholder="Exp : Beli Kado"
                                size="large"
                                onChange={(e) =>  setList(e.target.value)}
                                value={list}
                            />
                        </label>
                        <label>
                            Berapa Quantity :
                            <Input
                                placeholder="1xxxxx"
                                size="large"
                                onChange={(e) =>  setQuantity(e.target.value)}
                                value ={quantity}
                            />
                        </label>
                    
                    </div>
                </Modal>
            </main>
        </>
    )
}

export default Detail;