import React from "react"
import Navbar from "./components/organ/Navbar";
import DetailImage from './assets/detail.png'
import Image from "next/image";
import Head from "next/head";
import Button from "./components/atom/Button";
import { LeftOutlined } from '@ant-design/icons/lib/icons'
import Link from "next/link";
import CardDetail from "./components/atom/CardDetail";

const Detail = () => {
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>
                
                <div className='mx-36 pt-10 flex justify-between'>
                    <div className="text-3xl font-semibold flex justify-between items-center">
                        <Link href= '/'>
                            <LeftOutlined />
                        </Link>
                        Actifity
                    </div>
                    <Button
                        onClick={()=> console.log('helooo')}
                        className = 'text-lg font-semibold'
                    >
                        Tambah
                    </Button>
                </div>
                <div className='mx-36 pt-10 flex justify-center'>
                    <Image src={DetailImage} alt = 'detail' width={500} />
                </div>
                <div>
                    <CardDetail />
                </div>
            </main>
        </>
    )
}

export default Detail;