import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from './components/organ/Navbar/index'
import Button from './components/atom/Button/index'
import Link from 'next/link'
import Image from 'next/image'
import foto from './assets/foto.png'
import CardPrimary from './components/atom/Card'
import { RootContext } from './components/reducer'
import { useContext } from 'react'

export default function Home() {

  const contex = useContext(RootContext)
  const {dispatch, state} = contex
  console.log(contex.state)
  const message = {
    id:1,
    title : 'akannn',
    message : [{
        list : 'minum',
        quantity : 'lalala'
    }]
  }

  const message1 = {
    list : 'mana',
    quantity : 'lalalal'
  }

  const handleAddGroup = () => {
    dispatch({type:"ADD_GROUP", payload: message})
  }

  const handleDeleteGroup = (props : number) => {
    dispatch({type:'DELETE_GROUP', payload:props })
  }

  const handleAddItem = () => {
    dispatch({type:'ADD_ITEM', payload:message1})
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className='mx-36 pt-10 flex justify-between'>
          <h1 className='text-3xl font-semibold '>Actifity</h1>
          <Button
            onClick={handleAddGroup}
            className = 'text-lg font-semibold'
          >
            Tambah
          </Button>
        </div>
        <div className='flex justify-center gap-4 mx-36 flex-wrap mt-10'>
          {state.items[0]? 
          state.items.map((item, index) => 
          <div key={index}>
            <CardPrimary
              title = {item.title}
              onClick = {()=> handleDeleteGroup(index)}
              body = {item.message[0].list}
            />
          </div> ) : 
          <Link href='/'>
            <Image src={foto} alt = 'home' width={500} />
          </Link>}
        </div>
      </main>
    </>
  )
}
